- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    ~/.1password:
        mode: 0700
    ~/.ansible:
        mode: 0700
    ~/.config/lsd:
        mode: 0700
    ~/.config/gh:
        mode: 0700
    ~/.config/powershell:
        mode: 0700
    ~/.kube:
        mode: 0700
    ~/.local:
        mode: 0700
    ~/.ssh:
        mode: 0700
    ~/.terraform.d:
        mode: 0700

- link:
    ~/.vim: vim/vimfiles
    ~/.vimrc: vim/vimrc
    ~/.config/powershell/Microsoft.PowerShell_profile.ps1:
        force: true
        path: pwsh/profile/Microsoft.PowerShell_profile.ps1
    ~/.ssh/config:
        force: true
        path: ssh/config/devcontainer.cfg
    ~/.zshrc:
        force: true
        path: zsh/rc/devcontainer.zsh
    ~/.zprofile:
        force: true
        path: zsh/zprofile/devcontainer.zsh

- shell:
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.config/powershell/iterm3.custom.omp.json || cp -f oh-my-posh/iterm3.custom.omp.json ~/.config/powershell/ ]
    - [ test -f ~/.ssh/config  &&  chmod 600 ~/.ssh/config ]
    - [ test -f ~/.gitconfig   ||  cp -f git/config/linux.config ~/.gitconfig ]
