- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    ~/.1password:
        mode: 0700
    ~/.ansible:
        mode: 0700
    ~/.aws:
        mode: 0700
    ~/.config/lsd:
        mode: 0700
    ~/.config/fastfetch:
        mode: 0700
    ~/.kube:
        mode: 0700
    ~/.local:
        mode: 0700
    ~/.ssh:
        mode: 0700
    ~/.terraform.d:
        mode: 0700

- link:
    ~/.config/fastfetch/config.conf:
        force: true
        if: '[ `uname` = Darwin ]'
        path: fastfetch/mac_config.conf
    ~/.gvimrc: vim/gvimrc
    ~/.idlerc:
        force: true
        if: '[ `uname` = Darwin ]'
        path: python/idlerc/darwin
    ~/.vim: vim/vimfiles
    ~/.vimrc: vim/vimrc
    ~/.zshrc:
        force: true
        relink: true
        if: '[ `uname` = Darwin ]'
        path: zsh/rc/darwin.zsh
    ~/.zprofile:
        force: true
        relink: true
        if: '[ `uname` = Darwin ]'
        path: zsh/zprofile/darwin.zsh
    ~/.config/lsd/config.yaml:
        force: true
        relink: true
        if: '[ `uname` = Darwin ]'
        path: lsd/mac_config.yaml

- shell:
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.gitconfig    || cp -f git/mac/.gitconfig ~/ ]
    - [ test -f ~/.gitignore    || cp -f git/.gitignore ~/ ]
    - [ test -f ~/.ssh/config   || cp -f ssh/mac/config ~/.ssh/ ]
    - [ test -f ~/.ssh/config   && chmod 600 ~/.ssh/config ]
    - [ test -f ~/.hushlogin    || cp -f bash/.hushlogin ~/ ]
