- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    - ~/.ansible
    - ~/.aws
    - ~/.config/lsd
    - ~/.config/gh
    - ~/.config/glab-cli
    - ~/.kube
    - ~/.local
    - ~/.ssh
    - ~/.terraform.d

- link:
    ~/.vim: vim/vimfiles
    ~/.vimrc: vim/vimrc
    ~/.zshrc:
        force: true
        if: '[ `uname` = DragonFly ]'
        path: zsh/rc/dragonfly.zsh
    ~/.zprofile:
        force: true
        if: '[ `uname` = DragonFly ]'
        path: zsh/zprofile/dragonfly.zsh
    ~/.zlogout:
        force: true
        if: '[ `uname` = DragonFly ]'
        path: zsh/zlogout/dragonfly.zsh

- shell:
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.gitignore || cp -f git/.gitignore ~/ ]
    - [ test -f ~/.gitconfig || cp -f git/linux/.gitconfig ~/ ]
    - [ test -f ~/.ssh/config   || cp -f ssh/config ~/.ssh/ ]
    - [ test -f ~/.ssh/config   && chmod 600 ~/.ssh/config ]
