- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    - ~/AppData/Roaming/lsd
    - ~/AppData/Roaming/terraform.d
    - ~/Documents/oh-my-posh
    - ~/.aws
    - ~/.config/fastfetch
    - ~/.kube
    - ~/.local/bin
    - ~/.oh-my-zsh/cache/completions
    - ~/.ssh

- link:
    ~/.gitconfig:
        force: true
        path: git/config/git-bash.config
    ~/.gitignore:
        force: true
        path: git/.gitignore
    ~/.minttyrc:
        force: true
        path: mintty/minttyrc
    ~/vimfiles: vim/vimfiles
    ~/_gvimrc: vim/gvimrc
    ~/_vimrc: vim/vimrc_win
    ~/_vsvimrc: vim/vsvimrc
    ~/AppData/Roaming/lsd/config.yaml:
        create: true
        force: true
        path: lsd/windows_config.yaml
    ~/.zshrc:
        force: true
        path: zsh/rc/git-bash.zsh
    ~/.bashrc:
        force: true
        path: bash/rc/git-bash.sh
    ~/.bash_profile:
        force: true
        path: bash/profile/git-bash.sh


- shell:
    - [ test -f ~/.wslconfig                                        || cp -f wsl/.wslconfig ~/ ]
    - [ test -f ~/.ssh/config                                       || cp -f ssh/config/git_bash/config ~/.ssh/ ]
    - [ test -f ~/.ssh/config                                       && chmod 600 ~/.ssh/config ]
    - [ test -f ~/Documents/oh-my-posh/iterm3.custom.omp.json       || cp -f oh-my-posh/iterm3.custom.omp.json ~/Documents/oh-my-posh/ ]
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.oh-my-zsh/cache/completions/_kubectx             || cp -f zsh/completion/_kubectx ~/.oh-my-zsh/cache/completions ]
    - [ test -f ~/.oh-my-zsh/cache/completions/_kubens              || cp -f zsh/completion/_kubens  ~/.oh-my-zsh/cache/completions ]
    - [ test -f ~/.local/bin/kubectx                                || cp -f kubectx/kubectx ~/.local/bin && chmod 755 ~/.local/bin/kubectx ]
    - [ test -f ~/.local/bin/kubens                                 || cp -f kubectx/kubens  ~/.local/bin && chmod 755 ~/.local/bin/kubens  ]

