- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    ~/.1password:
        mode: 0700
    ~/.ansible:
        mode: 0700
    ~/.aws:
        mode: 0700
    ~/.config/lsd:
        mode: 0700
    ~/.config/gh:
        mode: 0700
    ~/.config/glab-cli:
        mode: 0700
    ~/.config/fastfetch:
        mode: 0700
    ~/.config/powershell:
        mode: 0700
    ~/.kube:
        mode: 0700
    ~/.local:
        mode: 0700
    ~/.ssh:
        mode: 0700
    ~/.terraform.d:
        mode: 0700

- link:
    ~/.agent-bridge.sh:
        force: true
        if: '[ `hostname` != "CPC-giseo-0SE1T" ] && [ `hostname` != "CPC-xyz-sth" ]'
        path: 1password/.agent-bridge.sh
    ~/.openssh-agent-bridge.sh:
        force: true
        if: '[ `hostname` = "CPC-giseo-0SE1T" ]'
        path: ssh/.agent-bridge.sh
    ~/.config/lsd/config.yaml:
        force: true
        if: '[ `uname` = Linux ]'
        path: lsd/linux_config.yaml
    ~/.config/powershell/Microsoft.PowerShell_profile.ps1:
        force: true
        path: pwsh/profile/Microsoft.PowerShell_profile.ps1
    ~/.vim: vim/vimfiles
    ~/.vimrc: vim/vimrc
    ~/.gitconfig:
        force: true
        if: '[ `uname` = Linux ]'
        path: git/config/wsl.config
    ~/.gitignore:
        force: true
        if: '[ `uname` = Linux ]'
        path: git/.gitignore
    ~/.zshrc:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/rc/wsl.zsh
    ~/.zprofile:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/zprofile/wsl.zsh
    ~/.zlogout:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/zlogout/wsl.zsh

- shell:
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.config/powershell/iterm3.custom.omp.json || cp -f oh-my-posh/iterm3.custom.omp.json ~/.config/powershell/ ]
    - [ test -f ~/.ssh/config   || cp -f ssh/config/linux.cfg ~/.ssh/config ]
    - [ test -f ~/.ssh/config   && chmod 600 ~/.ssh/config ]
    - [ test -f ~/.zshenv       || cp -f zsh/env/linux.env.zsh ~/.zshenv ]
    - [ test -f ~/.zshenv       && chmod 644 ~/.zshenv ]
