- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    - ~/.1password
    - ~/.ansible
    - ~/.aws
    - ~/.config/lsd
    - ~/.config/gh
    - ~/.config/glab-cli
    - ~/.config/fastfetch
    - ~/.kube
    - ~/.local
    - ~/.ssh
    - ~/.terraform.d

- link:
    ~/.agent-bridge.sh:
        force: true
        path: 1password/.agent-bridge.sh
    ~/.config/lsd/config.yaml:
        force: true
        if: '[ `uname` = Linux ]'
        path: lsd/linux_config.yaml
    ~/.config/fastfetch/config.conf:
        force: true
        if: '[ `uname` = Linux ]'
        path: fastfetch/wsl_config.conf
    ~/.vim: vim/vimfiles
    ~/.vimrc: vim/vimrc
    ~/.zshrc:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/rc/wsl.zsh
    ~/.zprofile:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/zprofile/wsl.zsh
    ~/.zlogout:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/zlogout/wsl.zsh

- shell:
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.gitignore || cp -f git/.gitignore ~/ ]
    - [ test -f ~/.gitconfig || cp -f git/wsl/.gitconfig ~/ ]
    - [ test -f ~/.ssh/config   || cp -f ssh/config ~/.ssh/ ]
    - [ test -f ~/.ssh/config   && chmod 600 ~/.ssh/config ]
