- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    ~/.ansible:
        mode: 0700
    ~/.aws:
        mode: 0700
    ~/.config/lsd:
        mode: 0700
    ~/.config/gh:
        mode: 0700
    ~/.config/glab-cli:
        mode: 0700
    ~/.config/fastfetch:
        mode: 0700
    ~/.kube:
        mode: 0700
    ~/.local:
        mode: 0700
    ~/.ssh:
        mode: 0700
    ~/.terraform.d:
        mode: 0700

- link:
    ~/.config/lsd/config.yaml:
        force: true
        if: '[ `uname` = Linux ]'
        path: lsd/linux_config.yaml
    ~/.config/fastfetch/config.conf:
        force: true
        if: '[ `uname` = Linux ]'
        path: fastfetch/wsl_config.conf
    ~/.vim: vim/vimfiles
    ~/.vimrc: vim/vimrc
    ~/.gitconfig:
        force: true
        if: '[ `uname` = Linux ]'
        path: git/config/linux.config
    ~/.gitignore:
        force: true
        if: '[ `uname` = Linux ]'
        path: git/.gitignore
    ~/.zshrc:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/rc/linux.zsh
    ~/.zprofile:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/zprofile/linux.zsh
    ~/.zlogout:
        force: true
        if: '[ `uname` = Linux ]'
        path: zsh/zlogout/linux.zsh

- shell:
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.ssh/config   || cp -f ssh/config ~/.ssh/ ]
    - [ test -f ~/.ssh/config   && chmod 600 ~/.ssh/config ]
    - [ test -f ~/.hushlogin    || cp -f bash/.hushlogin ~/ ]
