- defaults:
    link:
        create: true
        relink: true

- clean: ['~']

- create:
    - ~/.1password
    - ~/.ansible
    - ~/.config/lsd
    - ~/.config/gh
    - ~/.kube
    - ~/.local
    - ~/.ssh
    - ~/.terraform.d

- link:
    ~/.vim: vim/vimfiles
    ~/.vimrc: vim/vimrc
    ~/.ssh/config:
        force: true
        path: ssh/devcontainer/config
    ~/.zshrc:
        force: true
        path: zsh/rc/devcontainer.zsh
    ~/.zprofile:
        force: true
        path: zsh/zprofile/devcontainer.zsh

- shell:
    - [ test -f ~/.oh-my-zsh/custom/themes/agnoster2clock.zsh-theme || cp -f zsh/theme/agnoster2clock.zsh-theme ~/.oh-my-zsh/custom/themes ]
    - [ test -f ~/.gitconfig || cp -f git/linux/.gitconfig ~/ ]
    - [ test -f ~/.ssh/config   && chmod 600 ~/.ssh/config ]
