" Customization
set nocompatible
set hlsearch    " highlight all search results
set ignorecase  " do case insensitive search
set incsearch   " show incremental search results as you type
set number      " display line number
set noswapfile  " disable swap file
set noundofile  " disable undo file
set showmode
set nowrap
set autoindent
set smartindent
set expandtab
set tabstop=4
set shiftwidth=4
set shortmess+=I " Suppress startup message
syntax on

